# -*- coding: utf-8 -*-
"""GEN AI -2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oDxmef-Ttq8VlO5__pqKflOq7qEfbe0y
"""

from transformers import pipeline
sentiment_analyzer = pipeline("sentiment-analysis")
text = "I am feeling happy"
sentiment_result = sentiment_analyzer(text)
print("Sentiment analysis:")
print(f"Sentiment: {sentiment_result[0]['label']} (score: {sentiment_result[0]['score']:.2f})\n")

from transformers import pipeline
translator_en_to_fr = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")
text = "I am feeling happy"
translation_result = translator_en_to_fr(text)
print("Translation:")
print(f"Translated text: {translation_result[0]['translation_text']}\n")

!pip install pytesseract

import pytesseract
from PIL import Image
from transformers import pipeline

import os
print(os.path.isfile('/content/hari.jpg'))

from PIL import Image
from IPython.display import display

# Define input_image by opening the image file
input_image = Image.open('/content/hari.jpg')

# Now you can show and display the image without error
input_image.show()
display(input_image)

import pytesseract
from PIL import Image
import re

input_image = Image.open('/content/hari.jpg')

text_output = pytesseract.image_to_string(input_image, lang='eng').strip()

text_output = re.sub(r"\s+,", ",", text_output)

print(text_output)

image = Image.open('/content/hari.jpg')
extracted_text = pytesseract.image_to_string(image).strip()

if not extracted_text:
    print("No text found in the image.")
else:
    print(f"Extracted Text: {extracted_text}")
    sentiment_analyzer = pipeline("sentiment-analysis")
    sentiment_result = sentiment_analyzer(extracted_text)[0]
    #print("Sentiment analysis:")
    #print(f"Text: {extracted_text}")
    print(f"Sentiment: {sentiment_result['label']} (score: {sentiment_result['score']:.2f})")