# -*- coding: utf-8 -*-
"""GenAi1stlab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18d0Hw3i3u7hjFXf19fNaWobAUYo5ZP-W
"""

import math
n=int(input())
print(math.sqrt(n))

a=int(input("enter 1st num"))
b=int(input("enter 2nd num"))
c=a
a=b
b=c
print(a)
print(b)

n=int(input())
if(n>=0):
 print("num is positive")
else:
 print("num is negative")

n=int(input())
if(n%2==0):
 print("num is even")
else:
 print("num is odd")

import math
n=int(input())
print(math.factorial(n))

n=input()
if(n==n[::-1]):
  print("palindrome")
else:
  print("not palindrome")

import pandas as pd
data={ "Name":["sai", "priya","sinchana"],
      "Age":[20,25,27],
       "city":["bgl","hyd","chennai"]}
df=pd.DataFrame(data)
print(df)

df["Age"]

df[df["Age"]>25]

# 3-input AND gate implementation

def AND_gate_3(a, b, c):
    return a and b and c  # Logical AND for three inputs

# Test the AND gate
inputs = [
    (0, 0, 0),
    (0, 0, 1),
    (0, 1, 0),
    (0, 1, 1),
    (1, 0, 0),
    (1, 0, 1),
    (1, 1, 0),
    (1, 1, 1)
]

print("A B C | Output")
print("---------------")
for a, b, c in inputs:
    print(f"{a} {b} {c} | {int(AND_gate_3(a, b, c))}")