# -*- coding: utf-8 -*-
"""genai2exp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hG95Zo-dwd-kTyznHpTg8b6ZiJ7BnjEB
"""

from transformers import pipeline

sentiment_analyzer = pipeline("sentiment-analysis")
text = "I am feeling happy"
sentiment_result = sentiment_analyzer(text)

print("Sentiment analysis:")
print(f"Sentiment: {sentiment_result[0]['label']} score: {sentiment_result[0]['score']:.2f}")

from transformers import pipeline

translator_en_to_fr = pipeline("translation_en_to_fr", model="Helsinki-NLP/opus-mt-en-fr")
text = "I am feeling happy"
translation_result = translator_en_to_fr(text)

print("Translation:")
print(f"Translated text: {translation_result[0]['translation_text']}\n")

